=== RicharddeGraaf1/schemaTestsRichard/stop/1.3.0/imop-schemata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:sv="https://standaarden.overheid.nl/stop/imop/schemata/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="https://standaarden.overheid.nl/stop/imop/schemata/"
           version="1.3.0">
   <xs:annotation>
      <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/goto.html?to=stop&amp;id=xsd:br">"schemata-schema" van STOP.</xs:documentation>
      <xs:documentation>Dit schema definieert de schemakoppeling- en schemaversie-elementen voor STOP. Prefix sv staat voor  "schemaversie"</xs:documentation>
      <xs:documentation>Versie 1.3.0</xs:documentation>
      <xs:documentation>Documentatie op https://koop.gitlab.io/STOP/standaard/1.3.0/go/goto.html?to=stop&amp;id=xsd:sv</xs:documentation>
   </xs:annotation>
   <xs:element name="Versieoverzicht">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:Versieoverzicht"/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element ref="sv:versie"/>
            <xs:element maxOccurs="unbounded" ref="sv:Module"/>
         </xs:sequence>
         <xs:attributeGroup ref="sv:agSchemaVersie"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="versie" type="sv:dtSemverNr">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:versie"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="Module">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:Module"/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" ref="sv:localName"/>
            <xs:element maxOccurs="1" minOccurs="1" ref="sv:namespace"/>
            <xs:element maxOccurs="1" minOccurs="1" ref="sv:implementatie"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="localName" type="xs:NCName">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:localName"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="namespace" type="sv:dtNamespace">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:namespace"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="implementatie">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:implementatie"/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="1" ref="sv:Moduleversie"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="Moduleversie">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:Moduleversie"/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" ref="sv:introductieversie"/>
            <xs:element maxOccurs="1" minOccurs="1" ref="sv:schema"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="sv:schematron"/>
            <xs:element maxOccurs="1" minOccurs="0" ref="sv:heeftTransformatie"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="heeftTransformatie">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:heeftTransformatie"/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="sv:Transformatie"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="Transformatie">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:Transformatie"/>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" ref="sv:introductieversie"/>
            <xs:element maxOccurs="1" minOccurs="1" ref="sv:locatie"/>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="introductieversie" type="sv:dtSemverNr">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:introductieversie"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="schema" type="sv:dtLocatie">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:schema"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="schematron" type="sv:dtLocatie">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:schematron"/>
      </xs:annotation>
   </xs:element>
   <xs:element name="locatie" type="sv:dtLocatie">
      <xs:annotation>
         <xs:documentation source="https://koop.gitlab.io/STOP/standaard/1.3.0/go/go.html?id=xsd:sv:locatie"/>
      </xs:annotation>
   </xs:element>
   <!-- ATTRIBUTE GROUPS -->
   <xs:attributeGroup name="agSchemaVersie">
      <xs:attribute name="schemaversie" type="sv:dtSemverNr" use="required"/>
   </xs:attributeGroup>
   <!-- DATATYPES -->
   <xs:simpleType name="dtNamespace">
      <xs:restriction base="xs:anyURI"/>
   </xs:simpleType>
   <xs:simpleType name="dtLocatie">
      <xs:restriction base="xs:anyURI"/>
   </xs:simpleType>
   <xs:simpleType name="dtSemverNr">
      <xs:restriction base="xs:string"><!-- <xs:pattern
        value="(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-[a-zA-Z][a-zA-Z-]*){0,1}"/>--></xs:restriction>
   </xs:simpleType>
</xs:schema>

=== RicharddeGraaf1/schemaTestsRichard/1.4.1/lvbb/versie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Versieoverzicht xmlns="https://standaarden.overheid.nl/stop/imop/schemata/"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 schemaversie="1.3.0-ic"
                 xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/schemata/   https://standaarden.overheid.nl/stop/1.4.0-ic/imop-schemata.xsd">
  <versie>1.3.0-ic</versie>
  <Module>
    <localName>AanleveringBesluit</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-stop-aanlevering.xsd</schema>
        <schematron>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-aanlevering.sch</schematron>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>AanleveringKennisgeving</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-stop-aanlevering.xsd</schema>
        <schematron>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-aanlevering.sch</schematron>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>AanleveringInformatieObject</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-stop-aanlevering.xsd</schema>
        <schematron>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-aanlevering-io.sch</schematron>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>AanleveringRevisie</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.3.0-ic</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-stop-aanlevering.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>AanleveringRectificatie</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.3.0-ic</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-stop-aanlevering.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module> 
  <Module>
    <localName>AanleveringMededeling</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.3.0-ic</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-stop-aanlevering.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>   
  <Module>
    <localName>validatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>publicatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>validatieDirecteMutatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>directeMutatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>breekPublicatieAfOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>revisieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.3.0-ic</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>  
  <Module>
    <localName>manifest</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.3.0-ic/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
</Versieoverzicht>

=== RicharddeGraaf1/schemaTestsRichard/1.3/versie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Versieoverzicht xmlns="https://standaarden.overheid.nl/stop/imop/schemata/"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 schemaversie="2.0.0-rc"
                 xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/schemata/   https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/stop/1.3.0/imop-schemata.xsd">
  <versie>2.0.0-rc</versie>
  <Module>
    <localName>AanleveringBesluit</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-stop-aanlevering.xsd</schema>
        <schematron>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-aanlevering.sch</schematron>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>AanleveringKennisgeving</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-stop-aanlevering.xsd</schema>
        <schematron>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-aanlevering.sch</schematron>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>AanleveringInformatieObject</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/aanlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-stop-aanlevering.xsd</schema>
        <schematron>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-aanlevering-io.sch</schematron>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>validatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>publicatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>validatieDirecteMutatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>directeMutatieOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>raadpleegOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>breekPublicatieAfOpdracht</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>manifest</localName>
    <namespace>http://www.overheid.nl/2017/lvbb</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/refs/heads/main/1.3/lvbb-transport.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
</Versieoverzicht>

=== RicharddeGraaf1/schemaTestsRichard/lvbb-ozon/versie.xml
<?xml version="1.0" encoding="UTF-8"?>
<Versieoverzicht xmlns="https://standaarden.overheid.nl/stop/imop/schemata/"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 schemaversie="2.0.0-rc"
                 xsi:schemaLocation="https://standaarden.overheid.nl/stop/imop/schemata/   https://standaarden.overheid.nl/stop/2.0.0-rc/imop-schemata.xsd">
  <versie>1.6.0</versie>
  <Module>
    <localName>Consolidaties</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/uitlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/main/lvbb-ozon/lvbb-stop-uitlevering.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>OfficielePublicatie</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/uitlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/main/lvbb-ozon/lvbb-stop-uitlevering.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>UitleveringProefversieBesluit</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/uitlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/main/lvbb-ozon/lvbb-stop-uitlevering.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>WettechnischeInformatie</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/stop/uitlevering/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://raw.githubusercontent.com/RicharddeGraaf1/schemaTestsRichard/main/lvbb-ozon/lvbb-stop-uitlevering.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
  <Module>
    <localName>Vergunning</localName>
    <namespace>https://standaarden.overheid.nl/lvbb/vergunningsmetadata/</namespace>
    <implementatie>
      <Moduleversie>
        <introductieversie>1.0.0</introductieversie>
        <schema>https://standaarden.overheid.nl/lvbb/1.0.0/lvbb-vergunningsmetadata.xsd</schema>
      </Moduleversie>
    </implementatie>
  </Module>
</Versieoverzicht>
